version: '3'

services:
  backend:
    build:
      context: .
    volumes:
      - ./app/:/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - logbook
    links:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - logbook


  pgadmin4:
    image: dpage/pgadmin4
    user: "${UID}:${GID}" # to avoid permission issues
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin4:/var/lib/pgadmin
    ports:
      - "5433:80"
    depends_on:
      - postgres
    networks:
      - logbook

networks:
  logbook:
    driver: bridge

volumes:
  app:
  postgresql:
  pgadmin4: